p='DESIGN.md'
s=open(p).read()
n=0
def rep(old,new,count=1):
    global s,n
    assert s.count(old)>=1, old[:90]
    s=s.replace(old,new,count); n+=1
rep("  - ARMED lights the key that armed (COMBAT or a pin), and the pad tints red as today.",
    "  - ARMED lights the key that armed (COMBAT or a pin), and the pad tints red as today. A map tap while Fight is armed disarms it and is consumed (§6).")
rep("- **Text size is an input to the rule.** A message row is the face's 10 dp x-height (Atkinson Hyperlegible Next 0.496, VT323 0.400) × the Message size (0.85–1.4) × the system's text size (clamped 0.8–2, as `overlay.js` `osTextScale()` clamps it) × 1.35 leading: 27.2 dp at the defaults, 94.5 dp at VT323 × 1.4 × 2. The status band is 48 dp × the system's text size. `textMetrics({msgFont, msgSize, textScale})` returns both,",
    "- **Text size is an input to the rule.** A message row is the build's x-height, divided by the face's x-height ratio (Atkinson Hyperlegible Next 0.496, VT323 0.400), × the Message size (0.85–1.4) × the system's text size (clamped 0.8–2, as `overlay.js` `osTextScale()` clamps it) × 1.35 leading. The x-height is the web's 9.5 CSS px (Lucas, 2026-09-28, `overlay.js` `MSG_X`) or Android's 10 dp; each build passes its own. That gives 25.9 dp at the web's defaults (27.2 at Android's) and 89.8 dp at VT323 × 1.4 × 2. The status band is 48 dp × the system's text size. `textMetrics({msgFont, msgSize, textScale, xHeight})` returns both,")
rep("Only at twice the system text size with large message text (Atkinson × 1.4, or VT323 at any size) is the portrait glass of a 360x640 phone under 120 dp, and the result is marked degraded.",
    "Only at twice the system text size with large message text (Atkinson × 1.4, or VT323 × 1.2 or more) is the portrait glass of a 360x640 phone under 120 dp, and the result is marked degraded (still usable: the drawer fits, so the page draws it).")
rep("  - **phones, `mapCell: 'columns'` (default):** the cell that shows at least 34 of the level's 80 columns in landscape (today's count on Lucas's phone), with all 21 rows where they fit: T = clamp(min(landscape map width / 34, landscape map height / 21), 12, 20). That is 13.4 dp on Lucas's phone, 13.7 on 412-class phones, 12.7 on 390-class phones and 12 at 360. With Android's text cell (0.5625 as wide) the rows bind first: 15.2 dp, 53×21 in landscape.",
    "  - **phones, `mapCell: 'columns'` (default):** the cell that shows at least 34 of the level's 80 columns in landscape (today's count on Lucas's phone) where the 12 dp floor allows, with all 21 rows where they fit: T = clamp(min(landscape map width / 34, landscape map height / 21), 12, 20). That is 13.4 dp on Lucas's phone, 13.9 on 412-class phones, 12.8 on 390-class phones and 12 at 360. The floor binds where the landscape map is under 408 dp wide: the 360 class shows 23 columns. With Android's text cell (0.5625 as wide) the rows bind first: 15.35 dp, 52.8×21 in landscape.")
rep("  - **phones, `mapCell: 'rows'`:** the earlier rule, the cell whose 21 rows fill the landscape map, 12–20 dp (17.7 dp on Lucas's phone, 26×21), with the header over the banks whenever it fits.",
    "  - **phones, `mapCell: 'rows'`:** the earlier rule, the cell whose 21 rows fill the landscape map, 12–20 dp (17.8 dp on Lucas's phone, 25.6×21), with the header over the banks whenever it fits.")
rep("  - **choosing the glass:** the candidate showing the whole level wins, then one showing all 21 rows, then the most cells; on a tie, the header in the glass, then the bigger cell.",
    "  - **choosing the glass:** the candidate showing the whole level wins. Next comes one showing all 21 rows, which here means within half a row (at most a half-row pan), and it wins only while it shows at least 70% of its rival's cells (960x600: 714 against 993, 0.72). Then the most cells; on a tie, the header in the glass, then the bigger cell. Round 1 ranked the 21 rows strictly first, and on foldables and split views that picked a 120 dp column over a full-width map short by 0.03 of a row.\n  - **smaller keys never show less:** when the ranking's own pick at 46 or 52 dp keys would show fewer cells or less map than the next larger key size, the larger size's glass (its kind and its message rows) is used. Smaller keys never make the bank stand taller, and never push the header over the banks lower. Checked on 1,068,435 windows and by sweep §2.\n  - **a map that does not show the whole level stops at its 80 columns:** the map area is never wider than the level.")
rep("- **Zoom.** Pinch stores a factor of the device cell, not a pixel size. So it carries across windows and is shared by both orientations. The web writes it on lift, not on every move.",
    "- **Zoom.** In twin banks, pinch stores a factor of the device cell, not a pixel size, so it carries across windows and is shared by both orientations. It is twin's own prefs key, `zoomFactor`, starting at 1×. It is deliberately not seeded from classic's `zoom`, so the first twin session shows the default cell that test 5 compares. Classic keeps `zoom` in CSS px, read by today's `tileSize()` and clamped 8–96 by its pinch and wheel handlers, and twin never writes it. The web writes the factor on lift, not on every move.")
rep("- **Caseless mode** keeps every rect. The wells and bezel are not drawn, and the map may draw dimmed under the halos as context. The hero-safe area stays the map area.",
    "- **Caseless mode** keeps every rect. The wells and bezel are not drawn, and the map may draw dimmed under the halos as context. The halos, seams and ring stay hit areas over the canvas, so the guard works the same (§6). The hero-safe area stays the map area.")
open(p,'w').write(s)
print(n)
