p='DESIGN.md'
s=open(p).read()
n=0
def rep(old,new,count=1):
    global s,n
    assert s.count(old)>=1, old[:90]
    s=s.replace(old,new,count); n+=1
rep("The web port is built first, behind the \"Layout: twin banks / classic\" setting, default twin. Classic stays as it is, as the setting's other value and as the fallback.",
    "The web port is built first, behind the \"Layout: twin banks / classic\" setting, default twin. Classic stays as it is, as the setting's other value and as the fallback. Nothing twin adds reaches classic: the zoom factor has its own prefs key, `viewport-fit=cover` is written only for twin, and the `paranoid_confirmation` line is appended only for twin.")
rep("- `rebuild()`: read the size from the `svh` root, the budget for this display mode, the side-inset probe, the input mode and the text metrics (`textMetrics({msgFont, msgSize, textScale: osTextScale()})`), call `layout()`, and place every key absolutely in CSS px from `spec.controls`.",
    "- Before the first `layout()` while the layout is twin, write `viewport-fit=cover` into the viewport meta; switching to classic removes it. If a browser ignores the change at run time, the switch takes effect at the next load.\n- `rebuild()`: read the size from the `svh` root, the budget for this display mode, the side-inset probe, the input mode and the text metrics (`textMetrics({msgFont, msgSize, textScale: osTextScale(), xHeight: MSG_X})`, the page's own 9.5), call `layout()`. If the result is `usable: false`, or there is no spec, keep or bring back classic for this window (§12). Otherwise place every key absolutely in CSS px from `spec.controls`.")
rep("- Each key element's box is its hit cell, with the keycap drawn inset; a halo div per bank snaps within 8 dp and swallows 8–12 dp, only when a tap would travel (§6).",
    "- Each key element's box is its hit cell, with the keycap drawn inset. On the action pad the seams between keycaps (the drawn gap, at least 8 dp) are swallow strips. A halo div per bank snaps within 8 dp and swallows 8–12 dp. Both act whenever a tap would travel, Fight armed included (§6). `overlay.armed` is readable by `web.js`.")
rep("- Layers: COUNT (close on lift unless held 600 ms; Long rest's ×100–×400 on a hold) and HERE (slide-only from the pad centre, sticky from CONTEXT). Remove the chip rows, the context radial and the candidate fan. The layer name pill inside the map.",
    "- Layers: COUNT (close on lift unless held 600 ms; Long rest's ×100–×400 on a hold) and HERE (slide-only from the pad centre, sticky from CONTEXT). From CONTEXT, Ascend and Descend take a second tap: on the lit place in HERE, or on CONTEXT or the lit place when they are its one action. A dimmed place swallows. Remove the chip rows, the context radial and the candidate fan. The layer name pill inside the map.")
rep("- `data-tier` and `data-input` attributes; the Ctrl+Space prefix (Ctrl+Option+Space on macOS, Ctrl+Shift+Space on ChromeOS); the legends.",
    "- `data-tier` and `data-input` attributes; the Ctrl+; prefix (by `KeyboardEvent.code` `Semicolon`, taken before `keyCode()` turns it into `;`); the legends.\n- The ghost deck's habit guards while it is active: after a pad-centre hold that lifts without a slide, and after a hold of 380 ms or more on the old SACRIFICE spot (§6, item 8).")
rep("- `prefs.js`: `layout: 'twin'` (and `'classic'`), `mapCell: 'columns'`, `gripLift: 0`, `anchor: 'auto'`, `ghostDeck` (its session count); `zoom` becomes a factor of the device cell (migrate the old px value once).",
    "- `prefs.js`: `layout: 'twin'` (and `'classic'`), `mapCell: 'columns'`, `gripLift: 0`, `anchor: 'auto'`, `ghostDeck` (sessions in a row with no catch, this session's turns and last input time), `zoomFactor: 1` (twin's zoom, a factor of the device cell; not seeded from `zoom`). Classic's `zoom: 0` (CSS px) stays as it is and twin never writes it.")
rep("- `tileSize()` returns the device cell × the zoom factor; `placeView()` and the tap handler use",
    "- `tileSize()`, in twin, returns the device cell × `zoomFactor`; in classic it stays today's code (`zoom` in px when above 0, else fit the rows). The pinch and wheel handlers write `zoomFactor` in twin and `zoom` (clamped 8–96) in classic, as today. `placeView()` and the tap handler use")
rep("- `glassGestures()`: in its tap path (`up()`, `web.js:425–433`), when a tap would travel: the confirm ring, the 120 ms after a key lifts, the 200 ms after a drawer, modal or menu closes, and the ghost deck's preview. At --More--, in getpos, in menus, with a key armed or a layer open, taps pass as today.",
    "- `glassGestures()`: in its tap path (`up()`, `web.js:425–433`), whenever a tap would travel, which is whenever the core waits for a command:\n  - the confirm ring, the 120 ms ring rule after a key lifts, the 200 ms after a drawer, modal or menu closes, and the ghost deck's preview;\n  - with Fight armed (`overlay.armed`), a map tap disarms it and is consumed, never pushed as a click;\n  - with a layer open, a map tap closes it and is consumed, as today's scrim does.\n\n  At --More--, in getpos, and in menus or text windows, taps pass as today. In a direction prompt `nextKey()` keeps dropping clicks.")
rep("**`index.html`, `manifest.json`, `rolehack.css`, `defaults.nh`.** `viewport-fit=cover`, root sized in `svh`. A Fullscreen item in MENU on Android; an Add to Home Screen hint on iPhone. The CSS gains well, rim and bezel paint for the new layout and keeps the classic case. `defaults.nh` gains, on its own line:",
    "**`index.html`, `manifest.json`, `rolehack.css`, `web.js` `start()`.**\n- `index.html` keeps today's viewport meta; `overlay.js` adds `viewport-fit=cover` for twin. The twin root is sized in `svh`.\n- A Fullscreen item in MENU on Android, and an Add to Home Screen hint on iPhone.\n- The CSS gains well, rim and bezel paint for the new layout and keeps the classic case.\n- `defaults.nh` is unchanged. `start()` already appends the player's own option lines to it; only while the layout is twin, it also appends, on its own line:")
rep("The `+` keeps the defaults (pray, swim, trap: `src/options.c` `optfn_paranoid_confirmation`, `flags.paranoia_bits` defaults), so Pray stays confirmed and T and R always ask.",
    "The `+` keeps the defaults (pray, swim, trap: `src/options.c` `optfn_paranoid_confirmation`, `flags.paranoia_bits` defaults), so Pray stays confirmed and T and R always ask. Classic plays exactly as today. A switch of the Layout setting reaches the game's options at the next game start, because the options file is written once per start.")
rep("1. `layout.js` in, behind the setting; keys placed from the spec with no scale; the header stacked in the glass; today's chip rows and fans re-anchored inside the map rect; a 3-column drawer; snapshot-and-restore rebuilds; the `paranoid_confirmation` line.",
    "1. `layout.js` in, behind the setting; the classic fallback for unusable results; keys placed from the spec with no scale; the header stacked in the glass; today's chip rows and fans re-anchored inside the map rect; a 3-column drawer; snapshot-and-restore rebuilds; the `paranoid_confirmation` line (twin only).")
rep("2. The map cell and zoom factor; the tap-drift fix;",
    "2. The map cell and `zoomFactor`; the tap-drift fix;")
rep("3. Layers (COUNT, HERE), the FLICK legend's targets, the layer pill.",
    "3. Layers (COUNT, HERE, the two-tap stairs from CONTEXT), the FLICK legend's targets, the layer pill.")
rep("4. The guard: halos, the ring and the closing rules in the tap path, the ghost deck. **Brief test 2 (near misses).**",
    "4. The guard: halos and the action pad's seams, the ring, the closing rules and the armed-Fight rule in the tap path, the ghost deck and its habit guards. **Brief test 2 (near misses).**")
rep("5. `viewer.js`, the budget per display mode, insets, the desk dock and panels, Ctrl+Space.",
    "5. `viewer.js`, the budget per display mode, insets, the desk dock and panels, the Ctrl+; prefix.")
rep("The \"only when a tap would travel\" states must be exact: a missed state is either a lost --More-- tap or a guard that does not guard.",
    "The \"when a tap would travel\" states must be exact: a missed state is either a lost --More-- tap or a guard that does not guard. Fight armed in the overlay is such a state even though no prompt is up.")
rep("6. **The default cell is a judgement.** 13.4 dp tiles show today's 34 columns with all 21 rows; `mapCell: 'rows'` gives 17.7 dp and 26 columns. Test 5 decides.",
    "6. **The default cell is a judgement.** 13.4 dp tiles show today's 34 columns with all 21 rows; `mapCell: 'rows'` gives 17.8 dp and 25.6 columns. Test 5 decides.")
rep("8. **Android later.** The golden fixtures turn drift into a failing test only when the Android build runs them.",
    "8. **Android later.** The golden fixtures turn drift into a failing test only when the Android build runs them.\n9. **The 360 dp action pad.** COMBAT → CONTEXT is 2.6% against today's 1.7% even with the seams (§6). The stairs take a second tap, so the cost is a wasted tap or a prompt, not a level. If a 360-class phone is at hand, test 2 should include it.")
open(p,'w').write(s)
print(n)
