#!/usr/bin/env python3
# Written for Rolehack by Lucas Ruiz with Claude, 2026-09-28.
"""The tile palettes as the apps use them: one colour map per Colour vision mode.

Lucas's decisions (2026-09-28, colour-vision-tiles-2026-09-28.html): tile
palettes only inside the Colour vision modes -- Standard keeps today's tiles
exactly -- at the smallest search strength that keeps every family apart for
red-green (15) and tritan (9), and the strongest for monochrome (15), which
still leaves 12 pairs merged in simulation; those need marks drawn on their
tiles, and none are drawn yet.

A map takes a standard colour to its colour in the mode.  It holds the 11
entries of the tile table the search moved (cvd-tilepal-<cap>.json) and the
shades Rolehack's own tiles use outside the table (the phone's sheet only;
the web's sheet is all table colours).  A shade follows the table colour
nearest to it (CIEDE2000): not at all when that is a fixed one (skin, greys,
background), else by that colour's move in CIELAB, scaled by how saturated
the shade is next to it, so a dusty rose barely moves when red does.

  python3 cvd_tilegen.py [phone sheet]
writes cvd-tilemaps.json, cvd-tilemaps-java.txt, cvd-tilemaps-js.txt and
tilemaps-check.png (Rolehack's own tiles in each mode).
"""
import sys, json, math, pathlib, importlib.util
from PIL import Image
HERE = pathlib.Path(__file__).resolve().parent
SHEET = sys.argv[1] if len(sys.argv) > 1 else \
    '/root/RolehackDroid/sys/android/app/res/drawable-nodpi/default_16x16.png'
sys.argv = ['x', '/root/NetHack-web']
spec = importlib.util.spec_from_file_location('cvd', HERE / 'cvd.py')
cvd = importlib.util.module_from_spec(spec); spec.loader.exec_module(cvd)

CHOICE = {'redgreen': '15', 'tritan': '9', 'mono': '15'}
FIXED = set('.ALMNOQRSTUVWXYZ01')
hx = lambda h: tuple(int(h[i:i + 2], 16) for i in (1, 3, 5))
hexs = lambda c: '#%02x%02x%02x' % c

STD = {k: hx(v) for k, v in json.load(open(HERE / 'cvd-tilepal-15.json'))['palette'].items()}
MODE = {m: {k: hx(v) for k, v in json.load(open(HERE / f'cvd-tilepal-{c}.json'))['modes'][m]['palette'].items()}
        for m, c in CHOICE.items()}
VARY = [k for k in STD if k not in FIXED]

# CIELAB back to sRGB (D65), the inverse of cvd.lab()
def unlab(l):
    L, a, b = l
    fy = (L + 16) / 116; fx = fy + a / 500; fz = fy - b / 200
    f = lambda t: t ** 3 if t ** 3 > 0.008856 else (t - 16 / 116) / 7.787
    X, Y, Z = 0.95047 * f(fx), 1.0 * f(fy), 1.08883 * f(fz)
    r = 3.2404542 * X - 1.5371385 * Y - 0.4985314 * Z
    g = -0.9692660 * X + 1.8760108 * Y + 0.0415560 * Z
    bl = 0.0556434 * X - 0.2040259 * Y + 1.0572252 * Z
    enc = lambda v: 12.92 * v if v <= 0.0031308 else 1.055 * max(v, 0) ** (1 / 2.4) - 0.055
    return tuple(max(0, min(255, round(enc(v) * 255))) for v in (r, g, bl))

chroma = lambda l: math.hypot(l[1], l[2])
assert all(max(abs(p - q) for p, q in zip(unlab(cvd.lab(c)), c)) <= 1 for c in STD.values()), 'unlab'

im = Image.open(SHEET).convert('RGBA')
table = set(STD.values())
shades = sorted({p[:3] for p in im.getdata() if p[3] == 255 and p[:3] not in table})

maps, notes = {}, []
for mode, pal in MODE.items():
    m = {STD[k]: pal[k] for k in VARY if pal[k] != STD[k]}
    for c in shades:
        lc = cvd.lab(c)
        d, k = min((cvd.de2000(lc, cvd.lab(v)), k) for k, v in STD.items())
        if k in FIXED:
            if mode == 'redgreen':
                notes.append(f'{hexs(c)} stays: nearest {k} (fixed), dE {d:.1f}')
            continue
        lo, ln = cvd.lab(STD[k]), cvd.lab(pal[k])
        s = min(1.0, chroma(lc) / max(chroma(lo), 1e-6))
        out = unlab(tuple(x + s * (n - o) for x, o, n in zip(lc, lo, ln)))
        if out != c:
            m[c] = out
        if mode == 'redgreen':
            notes.append(f'{hexs(c)} follows {k} (dE {d:.1f}, x{s:.2f})')
    maps[mode] = m

(HERE / 'cvd-tilemaps.json').write_text(json.dumps({
    'choice': CHOICE, 'sheet': SHEET, 'shades': [hexs(c) for c in shades], 'notes': notes,
    'maps': {mode: {hexs(a): hexs(b) for a, b in m.items()} for mode, m in maps.items()}}, indent=1))

def pairs(m, fmt):
    return ', '.join(fmt(a, b) for a, b in sorted(m.items()))
NAME = {'redgreen': 'REDGREEN', 'tritan': 'TRITAN', 'mono': 'MONOCHROME'}
java = ['\t// generated by tools/cvd/cvd_tilegen.py (workspace), 2026-09-28: standard, then mode']
for mode, m in maps.items():
    java.append(f'\tprivate static final int[] {NAME[mode]} = {{')
    items = sorted(m.items())
    for i in range(0, len(items), 4):
        java.append('\t\t' + ' '.join('0x%06x, 0x%06x,' % ((a[0] << 16) | (a[1] << 8) | a[2], (b[0] << 16) | (b[1] << 8) | b[2])
                                     for a, b in items[i:i + 4]))
    java.append('\t};')
(HERE / 'cvd-tilemaps-java.txt').write_text('\n'.join(java) + '\n')
hexpair = lambda a, b: '0x%06x, 0x%06x' % ((a[0] << 16) | (a[1] << 8) | a[2], (b[0] << 16) | (b[1] << 8) | b[2])
js = ["// generated by tools/cvd/cvd_tilegen.py, 2026-09-28: pairs, a standard colour then the mode's;",
      '// protanopia and deuteranopia share one table, as on the phone (RhTilePalette)',
      f"const TILE_REDGREEN = [{pairs(maps['redgreen'], hexpair)}];",
      'const TILE_MODES = {',
      '  protanopia: TILE_REDGREEN,',
      '  deuteranopia: TILE_REDGREEN,',
      f"  tritanopia: [{pairs(maps['tritan'], hexpair)}],",
      f"  monochrome: [{pairs(maps['mono'], hexpair)}],",
      '};']
(HERE / 'cvd-tilemaps-js.txt').write_text('\n'.join(js) + '\n')

# check sheet: Rolehack's own tiles with shades, standard and each mode, as seen
W = im.size[0] // 16
own = sorted({(i % im.size[0]) // 16 + ((i // im.size[0]) // 16) * W
              for i, p in enumerate(im.getdata()) if p[3] == 255 and p[:3] not in table})
rows = [('standard', {}, 'normal')] + [(f'{mode} (normal eye)', maps[mode], 'normal') for mode in maps] + \
       [('redgreen as deuteranope', maps['redgreen'], 'deuteranopia'), ('tritan as tritanope', maps['tritan'], 'tritanopia'),
        ('mono as monochromat', maps['mono'], 'achromatopsia')]
S = 5
chk = Image.new('RGB', (len(own) * (16 * S + 6) + 6, len(rows) * (16 * S + 6) + 6), (30, 30, 30))
for r, (_, m, vis) in enumerate(rows):
    for j, t in enumerate(own):
        x0, y0 = (t % W) * 16, (t // W) * 16
        for y in range(16):
            for x in range(16):
                p = im.getpixel((x0 + x, y0 + y))
                c = m.get(p[:3], p[:3]) if p[3] == 255 else (30, 30, 30)
                if vis != 'normal':
                    c = tuple(max(0, min(255, int(round(v)))) for v in cvd.simulate(c, vis))
                for dy in range(S):
                    for dx in range(S):
                        chk.putpixel((6 + j * (16 * S + 6) + x * S + dx, 6 + r * (16 * S + 6) + y * S + dy), c)
chk.save(HERE / 'tilemaps-check.png')
print('shades', len(shades), 'own tiles', own)
print('\n'.join(notes))
for mode, m in maps.items():
    print(mode, len(m), 'entries')
print('rows:', ' / '.join(r[0] for r in rows))
